main/urls.py
from django.conf.urls import url
from . import views
app_name = "main"

urlpatterns = [

    url(r'^$',views.main, name = "main"),
    url(r'^home/$',views.home, name = "home"),

    url(r'^calendar/$',views.event, name = "event"),
    url(r'^createEvent/$',views.createEvent, name = "createEvent"),
    url(r'^editEvent/(?P<events_id>[0-9]+)$',views.editEvent, name = "editEvent"),
    url(r'^deleteEvent/(?P<events_id>[0-9]+)$',views.deleteEvent, name = "deleteEvent"),
    url(r'^event/$',views.event_page, name = "event_page"),

    url(r'^ad/$',views.admin_page, name = "admin_page"),
    url(r'^signin/$', views.signin, name="signin"),
    url(r'^logout/$',views.logout, name = "logout"),
    url(r'^naughty_page/$',views.naughty_page, name = "naughty_page"),
    url(r'^user_list/$',views.user_list, name = "user_list"),
    url(r'^user_coffees/(?P<user_id>[0-9]+)$',views.user_coffees, name = "user_coffees"),

    url(r'^send_order_email/(?P<year>\d{4})-(?P<month>\d{1,2})-(?P<day>\d{1,2})/$',views.send_order_email, name = "send_order_email"),
    url(r'^replecate_order/(?P<year>\d{4})-(?P<month>\d{1,2})-(?P<day>\d{1,2})/$',views.replecate_order, name = "replecate_order"),
    url(r'^received_order/(?P<order_id>[0-9]+)/(?P<year>\d{4})-(?P<month>\d{1,2})-(?P<day>\d{1,2})/$',views.received_order, name = "received_order"),
    url(r'^sent/(?P<year>\d{4})-(?P<month>\d{1,2})-(?P<day>\d{1,2})/$',views.sent, name = "sent"),
    url(r'^createCoffee/$',views.createCoffee, name = "createCoffee"),
    url(r'^editCoffee/(?P<coffee_id>[0-9]+)$',views.editCoffee, name = "editCoffee"),
    url(r'^deleteCoffee/(?P<coffee_id>[0-9]+)$',views.deleteCoffee, name = "deleteCoffee"),
    url(r'^createBean/$',views.createBean, name = "createBean"),
    url(r'^editBean/(?P<bean_id>[0-9]+)$',views.editBean, name = "editBean"),
    url(r'^deleteBean/(?P<bean_id>[0-9]+)$',views.deleteBean, name = "deleteBean"),
    url(r'^createRoast/$',views.createRoast, name = "createRoast"),
    url(r'^editRoast/(?P<roast_id>[0-9]+)$',views.editRoast, name = "editRoast"),
    url(r'^deleteRoast/(?P<roast_id>[0-9]+)$',views.deleteRoast, name = "deleteRoast"),
    url(r'^createSyrup/$',views.createSyrup, name = "createSyrup"),
    url(r'^editSyrup/(?P<syrup_id>[0-9]+)$',views.editSyrup, name = "editSyrup"),
    url(r'^deleteSyrup/(?P<syrup_id>[0-9]+)$',views.deleteSyrup, name = "deleteSyrup"),
    url(r'^createPowder/$',views.createPowder, name = "createPowder"),
    url(r'^editPowder/(?P<powder_id>[0-9]+)$',views.editPowder, name = "editPowder"),
    url(r'^deletePowder/(?P<powder_id>[0-9]+)$',views.deletePowder, name = "deletePowder"),
    url(r'^createOrder/(?P<coffee_id>[0-9]+)$',views.createOrder, name = "createOrder"),

]

spring17/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^main/', include('main.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Bean(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Roast(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Syrup(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Powder(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Coffee(models.Model):
    user= models.ForeignKey(User)
    name = models.CharField(max_length = 255)
    bean = models.ForeignKey(Bean)
    roast = models.ForeignKey(Roast)
    esspreso_shots = models.PositiveIntegerField(default = 1)
    water = models.FloatField(default = 0)
    steamed_milk = models.BooleanField(default = False)
    foam = models.FloatField(default = 0)
    powder = models.ManyToManyField(Powder, blank=True)
    syrup = models.ManyToManyField(Syrup, blank=True)
    extra_instructions = models.TextField()

    def __str__(self):
        return self.name

class Order(models.Model):
    user = models.ForeignKey(User)
    coffee = models.ForeignKey(Coffee)
    date = models.DateField()

    def __str__(self):
        return str(self.user)

class Events(models.Model):
    event_name = models.CharField(max_length=255,null=True,blank=True)
    start_date = models.DateTimeField(null=True,blank=True)
    end_date = models.DateTimeField(null=True,blank=True)
    event_type = models.CharField(max_length=10,null=True,blank=True)

    def __str__(self):
        return self.event_name

main/forms.py
from django import forms
from .models import *

class RoastForm(forms.ModelForm):
    class Meta:
        model = Roast
        fields = "__all__"

class BeanForm(forms.ModelForm):
    class Meta:
        model = Bean
        fields = "__all__"


class SyrupForm(forms.ModelForm):
    class Meta:
        model = Syrup
        fields = "__all__"

class PowderForm(forms.ModelForm):
    class Meta:
        model = Powder
        fields = "__all__"

class CoffeeForm(forms.ModelForm):
    class Meta:
        model = Coffee
        fields = "__all__"
        exclude = ["user"]

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['date']
        widgets = {
        'date': forms.DateInput(attrs={"type":"date"}),
        }

class SearchForm(forms.Form):
    date = forms.DateField(widget = forms.DateInput(attrs={"type":"date"}))

class SigninForm(forms.Form):
    username= forms.CharField()
    password= forms.CharField(widget=forms.PasswordInput)

class EventForm(forms.ModelForm):
    class Meta:
        model = Events
        fields = "__all__"
        widgets = {
        'start_date': forms.DateInput(attrs={"type":"date"}),
        'end_date': forms.DateInput(attrs={"type":"date"}),
        }

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import *
import datetime
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth import logout as django_logout
from django.contrib.auth import authenticate, login



def naughty_page(request):
    return render(request, 'main/naughty_page.html', {})

def home(request):
    context = {}
    if not request.user.is_authenticated():
        return redirect('/accounts/github/login')
    user = request.user
    context['user']=user
    if request.method=="POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            context['form']=form
            date = form.cleaned_data['date']
            context['today']=date
            order_list = Order.objects.filter(user=user, date=date)
            context["order_list"]=order_list
    else:
        form = SearchForm()
        context["form"]=form
        today = datetime.date.today()
        context['today']=today
        order_list = Order.objects.filter(user=user, date=today)
        context['order_list']=order_list
    coffee_list = Coffee.objects.filter(user=user)
    context['coffee_list']=coffee_list

    return render(request, "main/home.html", context)

def logout(request):
    django_logout(request)
    return redirect("main:main")

def main(request):

    context = {}

    return render(request, "main/index.html", context)




def createCoffee(request):
    context = {}
    if not request.user.is_authenticated():
        return redirect('/accounts/github/login')
    if request.method == "POST":
        form = CoffeeForm(request.POST)
        context["form"]=form
        if form.is_valid():
            coffee = form.save(commit=False)
            coffee.user = request.user
            coffee.save()
            form.save_m2m()
            return redirect("main:home")
        else:
            return render(request, "main/createCoffee.html", context)
    else:
        form = CoffeeForm()
        context["form"]=form
        return render(request, "main/createCoffee.html", context)

def editCoffee(request, coffee_id):
    context = {}
    if not request.user.is_authenticated():
        return redirect('/accounts/github/login')
    coffee = Coffee.objects.get(id=coffee_id)
    context["coffee"]=coffee

    if request.method == "POST":
        form = CoffeeForm(request.POST, instance=coffee)
        context["form"]=form
        if form.is_valid():
            coffee = form.save(commit=False)
            coffee.user = request.user
            coffee.save()
            form.save_m2m()
            return redirect("main:home")
        else:
            return render(request, "main/editCoffee.html", context)
    else:
        form = CoffeeForm(instance=coffee)
        context["form"]=form
        return render(request, "main/editCoffee.html", context)

def deleteCoffee(request, coffee_id):
    if not request.user.is_authenticated():
        return redirect('/accounts/github/login')
    Coffee.objects.get(id=coffee_id).delete()
    return redirect("main:home")

def createBean(request):
    context={}
    if not request.user.is_authenticated():
      return redirect('/admin')
    if not request.user.is_staff:
      return redirect("main:naughty_page")
    if request.method == "POST":
        form = BeanForm(request.POST)
        context["form"]=form
        if form.is_valid():
            form.save()
            return redirect("main:admin_page")
        else:
            return render(request, "main/createBean.html", context)
    else:
        form = BeanForm()
        context["form"]=form
        return render(request, "main/createBean.html", context)

def editBean(request, bean_id):
    context = {}
    if not request.user.is_authenticated():
      return redirect('/admin')
    if not request.user.is_staff:
      return redirect("main:naughty_page")
    bean = Bean.objects.get(id=bean_id)
    context["bean"]=bean

    if request.method == "POST":
        form = BeanForm(request.POST, instance=bean)
        context["form"]=form
        if form.is_valid():
            form.save()
            return redirect("main:admin_page")
        else:
            return render(request, "main/editBean.html", context)
    else:
        form = BeanForm(instance=bean)
        context["form"]=form
        return render(request, "main/editBean.html", context)

def deleteBean(request, bean_id):
    if not request.user.is_authenticated():
      return redirect('/admin')
    if not request.user.is_staff:
      return redirect("main:naughty_page")
    Bean.objects.get(id=bean_id).delete()
    return redirect("main:admin_page")

def createRoast(request):
    context={}
    if not request.user.is_authenticated():
      return redirect('/admin')
    if not request.user.is_staff:
      return redirect("main:naughty_page")
    if request.method == "POST":
        form = RoastForm(request.POST)
        context["form"]=form
        if form.is_valid():
            form.save()
            return redirect("main:admin_page")
        else:
            return render(request, "main/createRoast.html", context)
    else:
        form = RoastForm()
        context["form"]=form
        return render(request, "main/createRoast.html", context)

def editRoast(request, roast_id):
    context = {}
    if not request.user.is_authenticated():
      return redirect('/admin')
    if not request.user.is_staff:
      return redirect("main:naughty_page")
    roast = Roast.objects.get(id=roast_id)
    context["roast"]=roast

    if request.method == "POST":
        form = RoastForm(request.POST, instance=roast)
        context["form"]=form
        if form.is_valid():
            form.save()
            return redirect("main:admin_page")
        else:
            return render(request, "main/editRoast.html", context)
    else:
        form = RoastForm(instance=roast)
        context["form"]=form
        return render(request, "main/editRoast.html", context)

def deleteRoast(request, roast_id):
    if not request.user.is_authenticated():
      return redirect('/admin')
    if not request.user.is_staff:
      return redirect("main:naughty_page")
    Roast.objects.get(id=roast_id).delete()
    return redirect("main:admin_page")

def createSyrup(request):
    context={}
    if not request.user.is_authenticated():
      return redirect('/admin')
    if not request.user.is_staff:
      return redirect("main:naughty_page")
    if request.method == "POST":
        form = SyrupForm(request.POST)
        context["form"]=form
        if form.is_valid():
            form.save()
            return redirect("main:admin_page")
        else:
            return render(request, "main/createSyrup.html", context)
    else:
        form = SyrupForm()
        context["form"]=form
        return render(request, "main/createSyrup.html", context)

def editSyrup(request, syrup_id):
    context = {}
    if not request.user.is_authenticated():
      return redirect('/admin')
    if not request.user.is_staff:
      return redirect("main:naughty_page")
    syrup = Syrup.objects.get(id=syrup_id)
    context["syrup"]=syrup

    if request.method == "POST":
        form = SyrupForm(request.POST, instance=syrup)
        context["form"]=form
        if form.is_valid():
            form.save()
            return redirect("main:admin_page")
        else:
            return render(request, "main/editSyrup.html", context)
    else:
        form = SyrupForm(instance=syrup)
        context["form"]=form
        return render(request, "main/editSyrup.html", context)

def deleteSyrup(request, syrup_id):
    if not request.user.is_authenticated():
      return redirect('/admin')
    if not request.user.is_staff:
      return redirect("main:naughty_page")
    Syrup.objects.get(id=syrup_id).delete()
    return redirect("main:admin_page")

def createPowder(request):
    context={}
    if not request.user.is_authenticated():
      return redirect('/admin')
    if not request.user.is_staff:
      return redirect("main:naughty_page")
    if request.method == "POST":
        form = PowderForm(request.POST)
        context["form"]=form
        if form.is_valid():
            form.save()
            return redirect("main:admin_page")
        else:
            return render(request, "main/createPowder.html", context)
    else:
        form = PowderForm()
        context["form"]=form
        return render(request, "main/createPowder.html", context)

def editPowder(request, powder_id):
    context = {}
    if not request.user.is_authenticated():
      return redirect('/admin')
    if not request.user.is_staff:
      return redirect("main:naughty_page")
    powder = Powder.objects.get(id=powder_id)
    context["powder"]=powder

    if request.method == "POST":
        form = PowderForm(request.POST, instance=powder)
        context["form"]=form
        if form.is_valid():
            form.save()
            return redirect("main:admin_page")
        else:
            return render(request, "main/editPowder.html", context)
    else:
        form = PowderForm(instance=powder)
        context["form"]=form
        return render(request, "main/editPowder.html", context)

def deletePowder(request, powder_id):
    if not request.user.is_authenticated():
      return redirect('/admin')
    if not request.user.is_staff:
      return redirect("main:naughty_page")
    Powder.objects.get(id=powder_id).delete()
    return redirect("main:admin_page")


def createOrder(request, coffee_id):
    context={}
    if not request.user.is_authenticated():
        return redirect('/accounts/github/login')
    coffee = Coffee.objects.get(id=coffee_id)
    context['coffee']=coffee
    if request.method == "POST":
        form = OrderForm(request.POST)
        context['form']=form
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.coffee = coffee

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

    <head>

        <link href="{% static '/bootstrap-3.3.7-dist/css/bootstrap.css' %}" rel="stylesheet"/>
        <script src="{% static '/bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
        <meta charset="UTF-8"/>
        <title>Coffee</title>
    </head>
    <style>
        #jumbo{
        background-image: url("{% static 'main/Coffee.jpg' %}");
        background-size: 100%;
        background-repeat: no-repeat;
        }

    </style>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"> Hello {{request.user}}</a>

                </div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'main:home' %}">Homepage</a>

                </div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                      <a class="navbar-brand" href="{% url 'main:event' %}">Events</a>

                    {% if not request.user.is_staff %}
                    <a class="navbar-brand" href="#">Navigate</a>
                    {% else %}
                    <a class="navbar-brand" href="{% url 'main:admin_page' %}">Admin Page</a>
                    {% endif %}
                </div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    {% if request.user.is_authenticated %}
                      <a class="navbar-brand" href="{% url 'main:logout' %}">Logout</a>
                    {% endif %}
                </div>

                <form class="navbar-form navbar-right">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">contact us</a></li>
                </ul>
            </div><!-- /.container-fluid -->
        </nav>

        <div class="container">


            <div id="jumbo" class="jumbotron text-center" style="color:white">

                <h1>
                    {% block header %}
                    {% endblock %}
                </h1>
            </div>

            {% block content %}
            {% endblock %}

        </div>

        <div>This site was created by Nour Al-Shaiji & Haya Al-Humaidi</div>
    </body>
</html>

main/templates/main/createCoffee.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

<html>
  {% block header %}
  <head>
    <meta charset="utf-8">
    <title>Create Coffee</title>

  </head>
  {% endblock %}
    {% block content %}
  <body>
    <form class="" action="{% url 'main:createCoffee' %}" method="post">
      {% csrf_token %}
      {{form|crispy}}
    <input type="submit" name="" value="Create">
    </form>
  </body>
  {% endblock %}
</html>

main/templates/main/createEvent.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

<html>
  {% block header %}
  <head>
    <meta charset="utf-8">
    <title>Add Event</title>

  </head>
  {% endblock %}
    {% block content %}
  <body>
    <form class="" action="{% url 'main:createEvent' %}" method="post">
      {% csrf_token %}
      {{form|crispy}}
    <input type="submit" name="" value="Create">
    </form>
  </body>
  {% endblock %}
</html>

main/templates/main/createOrder.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Create Order</title>
    <link href="{% static '/bootstrap-3.3.7-dist/css/bootstrap.css' %}" rel="stylesheet"/>
    <script src="{% static '/bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
  </head>
  <body>
    <form class="" action="{% url 'main:createOrder' coffee_id=coffee.id %}" method="post">
      {% csrf_token %}
      {{form|crispy}}
    <input type="submit" name="" value="Order">
    </form>
  </body>
</html>

main/templates/main/createPowder.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Create Powder</title>
    <link href="{% static '/bootstrap-3.3.7-dist/css/bootstrap.css' %}" rel="stylesheet"/>
    <script src="{% static '/bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
  </head>
  <body>
    <form class="" action="{% url 'main:createPowder' %}" method="post">
      {% csrf_token %}
      {{form|crispy}}
    <input type="submit" name="" value="Create">
    </form>
  </body>
</html>

main/templates/main/createRoast.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Create Roast</title>
    <link href="{% static '/bootstrap-3.3.7-dist/css/bootstrap.css' %}" rel="stylesheet"/>
    <script src="{% static '/bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
  </head>
  <body>
    <form class="" action="{% url 'main:createRoast' %}" method="post">
      {% csrf_token %}
      {{form|crispy}}
    <input type="submit" name="" value="Create">
    </form>
  </body>
</html>

main/templates/main/createSyrup.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Create Syrup</title>
    <link href="{% static '/bootstrap-3.3.7-dist/css/bootstrap.css' %}" rel="stylesheet"/>
    <script src="{% static '/bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
  </head>
  <body>
    <form class="" action="{% url 'main:createSyrup' %}" method="post">
      {% csrf_token %}
      {{form|crispy}}
    <input type="submit" name="" value="Create">
    </form>
  </body>
</html>

main/templates/main/editBean.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit Bean</title>
    <link href="{% static '/bootstrap-3.3.7-dist/css/bootstrap.css' %}" rel="stylesheet"/>
    <script src="{% static '/bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
  </head>
  <body>
    <form class="" action="{% url 'main:editBean' bean_id=bean.id %}" method="post">
      {% csrf_token %}
      {{form|crispy}}
    <input type="submit" name="" value="Edit">
    </form>
  </body>
</html>

main/templates/main/editPowder.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit Powder</title>
    <link href="{% static '/bootstrap-3.3.7-dist/css/bootstrap.css' %}" rel="stylesheet"/>
    <script src="{% static '/bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
  </head>
  <body>
    <form class="" action="{% url 'main:editPowder' powder_id=powder.id %}" method="post">
      {% csrf_token %}
      {{form|crispy}}
    <input type="submit" name="" value="Edit">
    </form>
  </body>
</html>

main/templates/main/editRoast.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit Roast</title>
    <link href="{% static '/bootstrap-3.3.7-dist/css/bootstrap.css' %}" rel="stylesheet"/>
    <script src="{% static '/bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
  </head>
  <body>
    <form class="" action="{% url 'main:editRoast' roast_id=roast.id %}" method="post">
      {% csrf_token %}
      {{form|crispy}}
    <input type="submit" name="" value="Edit">
    </form>
  </body>
</html>

main/templates/main/homepage.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %} Welcome to ur Coffee Directory {% endblock %}
{% block content %}

<!DOCTYPE html>
<html>
 <head>
   <link rel='stylesheet' href="{% static '/fullcalendar/fullcalendar.css' %}" />
   <link href="{% static '/fullcalendar/scheduler.css' %}" rel='stylesheet' />
   <script src="{% static '/fullcalendar/lib/jquery.min.js' %}"></script>
   <script src="{% static '/fullcalendar/lib/moment.min.js' %}"></script>
   <script src="{% static '/fullcalendar/fullcalendar.js' %}"></script>
   <script src="{% static '/fullcalendar/scheduler.js' %}"></script>

   <script>
   $(document).ready(function() {

           $('#calendar').fullCalendar({
               defaultDate: '2017-06-09',
               editable: true,
               eventLimit: true, // allow "more" link when too many events
               events: [
                   {% for i in events %}
                   {
                       title: "{{ i.event_name}}",
                       start: '{{ i.start_date|date:"Y-m-d" }}',
                       end: '{{ i.end_date|date:"Y-m-d" }}',

                   },
                   {% endfor %}

               ]
           });

       });

   </script>
   <meta charset="utf-8">
   <title></title>
 </head>
 <body>
   <div id='calendar'></div>
 </body>
 <hr>
 {% if request.user.is_staff %}
 <a href="{% url 'main:event_page' %}" class="btn btn-primary" role="button">Go to Events Page</a>
 {% endif %}
 {% endblock %}
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}


{% block header %} Welcome to ur Coffee Directory {% endblock %}
{% block content %}
<div class="row">
 <h1> Who are you ? </h1>
 <hr>

   <div class="col-sm-5 col-md-2">
     <div class="thumbnail">
       <div class="caption">

         <p>
           <a href="{% url 'main:home' %}" class="btn btn-primary" role="button">Im a User</a>
           <a href="{% url 'main:admin_page' %}" class="btn btn-default" role="button">Im an Admin</a>
         </p>
       </div>
     </div>
   </div>


{% endblock %}

main/templates/main/naughty_page.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html>
  <head>

    <title>NAUGHTY</title>

  </head>
  <body>
<div> what are u trying to do !!!!!!!!!! </div>

  </body>
</html>

main/templates/main/user_list.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>User List</title>
    <link href="{% static '/bootstrap-3.3.7-dist/css/bootstrap.css' %}" rel="stylesheet"/>
    <script src="{% static '/bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
  </head>
  <body>
  {% for user in user_list %}
  <a href="{% url 'main:user_coffees' user_id=user.id %}"><div class="col col-sm-3">{{user}}</div></a>
  {% endfor %}
  </body>
</html>